sonar.projectKey=Univers42_osionos
sonar.organization=univers42
sonar.projectName=osionos
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.typescript.tsconfigPath=tsconfig.json
sonar.scm.disabled=true
sonar.scm.exclusions.disabled=true
sonar.coverage.exclusions=**/*

sonar.exclusions=vendor/**,node_modules/**,build/**,dist/**,coverage/**,.vite/**,playwright-report/**,test-results/**,audit/**,docker/**,scripts/**,src/shared/lib/markengine/**,src/**/*.css,src/**/*.scss,src/data/seedUsers.json
sonar.test.exclusions=tests/**/mediaPlaceholderHarness.*,tests/**/readOnlyHarness.*