import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1500, height: 950 } });
const page = await ctx.newPage();
await page.goto("https://localhost:4322", { waitUntil: "domcontentloaded", timeout: 30000 });
await page.getByRole("button", { name: /Start free/i }).first().click();
await page.locator("#portal[open]").waitFor({ timeout: 15000 });
await page.locator('[data-auth-switch="login"]').click();
await page.getByRole("textbox", { name: "Email" }).fill("dylan@gmail.com");
await page.getByRole("textbox", { name: "Password" }).fill("Osionos123!");
await page.locator("#portal [data-login-submit]").click();
await page.waitForURL((u) => u.port === "3001", { timeout: 45000 });
await page.waitForFunction(() => Boolean(localStorage.getItem("osionos:bridge-session")), null, { timeout: 45000 });
await page.waitForTimeout(5000);
await page.getByRole("button", { name: /Delivery Wiki/i }).first().click();
await page.waitForTimeout(7000);
await page.evaluate(() => { document.documentElement.dataset.theme = "dark"; });
await page.waitForTimeout(1500);
await page.mouse.move(880, 500);
await page.mouse.wheel(0, 1100);
await page.waitForTimeout(2500);
await page.mouse.move(60, 500);
await page.waitForTimeout(800);
await page.screenshot({ path: "/app/test-results/embed-dark2-rest.png" });
const block = page.locator(".osionos-object-database-single-view").nth(2);
await block.hover();
await page.waitForTimeout(900);
await page.screenshot({ path: "/app/test-results/embed-dark2-hover.png" });
await browser.close();
console.log("DONE");
